name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Teste e Coverage
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0 
      - name: Install Dependencies
        run: yarn
      - name: Test and Coverage
        run: yarn jest --coverage
